### ISSUE TITLE
please include a file with the license text in the git repo and in published crates

### ISSUE THREAD

**Issue by decathorpe** [bitvecto-rs/radium#6]
There exist lots of variants of *the* "MIT" license. Without a license text in the repository, it is not clear which variant is applicable.

For example, the Fedora project recognises over 20 different variants: https://fedoraproject.org/wiki/Licensing:MIT

Please include a license text in this repo, and also add the file to the "include" array in Cargo.toml, so it will be included in the published crates as well.

This is a requirement for applying MIT-style licenses correctly (GitHub license page headers show this, for example [here](https://github.com/myrrlyn/bitvec/blob/develop/LICENSE.txt), and it's mentioned [on choosealicense.com](https://choosealicense.com/licenses/mit/) as well). Most Rust projects licensed under the terms of an MIT license seem to have chosen the MIT License variant that's used by the linked GitHub example (bitvec), which the Fedora Project categorizes as "Modern Style with sublicense".

**Comment by myrrlyn** [comment]
This will be published as `0.6.2` later this year. Thank you again for the reports!
